kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: tasks-ms1-v1
  namespace: luigi3-dev
  labels:
    build: tasks
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'tasks-ms1-v1:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: luigi3-dev
        name: 'wildfly:latest'
  postCommit: {}
  source:
    type: Binary
    binary: {}
  triggers:
    - type: GitHub
      github:
        secret: sk6F38YBYu5EnfhU9qjf
    - type: Generic
      generic:
        secret: oteMKZyGa22WbYOpsOcz
  runPolicy: Serial
